version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    # 不覆蓋應用代碼，只掛載數據目錄
    volumes:
      - ./data:/app/data
      - ./services:/app/services
    restart: unless-stopped